# Generated by Django 2.1.2 on 2019-03-04 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamada', models.PositiveSmallIntegerField()),
                ('nome', models.CharField(max_length=70)),
                ('is_lider', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaDaTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.MateriaDaTurma')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_aluno', models.BooleanField(default=False, verbose_name='student status')),
                ('is_professor', models.BooleanField(default=False, verbose_name='teacher status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_escola', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProvaAplicada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='ProvaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.MateriaDaTurma')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicio', models.TimeField()),
                ('s1', models.TimeField()),
                ('s2', models.TimeField()),
                ('s3', models.TimeField()),
                ('s4', models.TimeField()),
                ('s5', models.TimeField()),
                ('horaFim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TurnoAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaDaSemana', models.PositiveSmallIntegerField(choices=[(1, 'sabado'), (2, 'segunda-feira'), (3, 'terca-feira'), (4, 'quarta-feira'), (5, 'quinta-feira'), (6, 'sexta-feira'), (7, 'sabado')])),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Horario')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Turma')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Turno')),
            ],
        ),
        migrations.AddField(
            model_name='provabase',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Turma'),
        ),
        migrations.AddField(
            model_name='provaaplicada',
            name='provaBase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.ProvaBase'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='turnoAula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.TurnoAula'),
        ),
        migrations.AddField(
            model_name='materiadaturma',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.Professor'),
        ),
        migrations.AddField(
            model_name='materiadaturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Turma'),
        ),
        migrations.AddField(
            model_name='horario',
            name='turma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='horario', to='escola.Turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escola.Turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL),
        ),
    ]
