# Generated by Django 2.1.2 on 2019-03-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='cod',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='nome',
            field=models.CharField(default=9, max_length=30),
            preserve_default=False,
        ),
    ]
