# Generated by Django 2.1.2 on 2019-03-04 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escola', '0003_auto_20190304_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cod_especial', models.PositiveSmallIntegerField(choices=[(0, 'Não especifico'), (1, 'Lider'), (2, 'Vice-lider'), (3, 'Suplente'), (4, 'Tesoureiro'), (5, 'Prof. Regente')])),
                ('ativo', models.BooleanField(default=True)),
                ('ocupante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Turma')),
            ],
            options={
                'permissions': (('can_add_cargo', 'Pode criar Cargo'), ('can_edit_cargo', 'Pode editar Cargo'), ('can_delete_cargo', 'Pode deletar Cargo'), ('can_designar_cargo', 'Pode designar alguem para o cargo')),
            },
        ),
    ]
