# Generated by Django 2.1.2 on 2019-03-04 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_auto_20190304_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='num',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='nome',
            field=models.CharField(default='SEM NOME', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Turma'),
        ),
        migrations.AlterField(
            model_name='cargoturma',
            name='ocupante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materiadaturma',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Professor'),
        ),
        migrations.AlterField(
            model_name='turnoaula',
            name='diaDaSemana',
            field=models.PositiveSmallIntegerField(choices=[(1, 'domingo'), (2, 'segunda-feira'), (3, 'terca-feira'), (4, 'quarta-feira'), (5, 'quinta-feira'), (6, 'sexta-feira'), (7, 'sabado')]),
        ),
    ]
