# Generated by Django 2.1.2 on 2019-03-04 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_auto_20190304_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.MateriaDaTurma'),
        ),
    ]
