# Generated by Django 2.1.2 on 2019-03-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_auto_20190304_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiadaturma',
            name='abreviacao',
            field=models.CharField(default='AAA', max_length=5),
            preserve_default=False,
        ),
    ]
