# Generated by Django 2.1.2 on 2019-03-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('escola', '0010_auto_20190305_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cor',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
