# Generated by Django 2.1.2 on 2019-03-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0011_auto_20190305_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'permissions': (('can_add_professor', 'Pode adicionar um novo Professor'), ('can_edit_professor', 'Pode editar um professor'), ('can_delete_professor', 'Pode deletar um professor'))},
        ),
    ]
