# Generated by Django 2.1.7 on 2019-03-18 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('escola', '0014_auto_20190314_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'permissions': (('edit_aluno', 'Pode editar um aluno.'), ('can_delete_aluno', 'Pode deletar um aluno.'))},
        ),
        migrations.AlterModelOptions(
            name='materiadaturma',
            options={'permissions': (('can_add_materia', 'Pode adicionar uma novo Materia'), ('can_edit_materia', 'Pode editar uma materia'), ('can_delete_materia', 'Pode deletar uma materia'))},
        ),
        migrations.AlterModelOptions(
            name='tarefa',
            options={'permissions': (('can_add_tarefa', 'Pode adicionar uma nova tarefa.'), ('can_edit_tarefa', 'Pode editar uma tarefa.'), ('can_delete_tarefa', 'Pode deletar uma tarefa.'))},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'permissions': (('can_add_turma', 'Pode criar turmas'), ('can_edit_turma', 'Pode editar turmas'), ('can_delete_turma', 'Pode deletar turmas'), ('can_populate_turma', 'Pode popular turmas'), ('can_add_aluno', 'Pode adicionar um aluno a turma.'))},
        ),
        migrations.AddField(
            model_name='turma',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='turma_lider', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='turma',
            name='regente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='turma_regente', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='turma',
            name='vicelider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='turma_vicelider', to='auth.Group'),
        ),
    ]
