# Generated by Django 2.1.7 on 2019-03-20 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0016_auto_20190320_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='materiadaturma',
            options={'permissions': (('can_edit_materia', 'Pode editar uma materia'), ('can_delete_materia', 'Pode deletar uma materia'))},
        ),
        migrations.AlterModelOptions(
            name='tarefa',
            options={'permissions': (('can_edit_tarefa', 'Pode editar uma tarefa.'), ('can_delete_tarefa', 'Pode deletar uma tarefa.'))},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'permissions': (('can_add_turma', 'Pode criar turmas'), ('can_edit_turma', 'Pode editar turmas'), ('can_delete_turma', 'Pode deletar turmas'), ('can_populate_turma', 'Pode popular turmas'), ('can_add_aluno', 'Pode adicionar um aluno a turma.'), ('editar_horario', 'Pode editar o horario.'), ('can_add_materia', 'Pode adicionar uma materia a turma.'), ('can_add_tarefa', 'Pode adicionar uma tarefa.'))},
        ),
    ]
