# Generated by Django 2.1.7 on 2019-03-28 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0017_auto_20190320_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provaaplicada',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='provaaplicada',
            name='provaBase',
        ),
        migrations.RemoveField(
            model_name='provabase',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='provabase',
            name='turma',
        ),
        migrations.DeleteModel(
            name='ProvaAplicada',
        ),
        migrations.DeleteModel(
            name='ProvaBase',
        ),
    ]
