# Generated by Django 2.1.7 on 2019-03-28 14:32

from django.db import migrations, models
import django.db.models.deletion
import escola.customFields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('escola', '0018_auto_20190327_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaConteudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', escola.customFields.ColorField(default='#0e74ce', max_length=10)),
            ],
            options={
                'verbose_name': 'Categoria de Link de Conteudos',
                'verbose_name_plural': 'Categorias de Links de Conteudos',
            },
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('conteudo_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.Conteudo')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Professor')),
            ],
            options={
                'verbose_name': 'Conteudo',
                'verbose_name_plural': 'Conteudos',
                'permissions': (('can_add_in_materia', 'Pode adicionar esse conteudo à uma materia.'),),
            },
        ),
        migrations.CreateModel(
            name='LinkConteudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.CategoriaConteudo')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Link de Conteudo',
                'verbose_name_plural': 'Links de Conteudos',
            },
        ),
        migrations.AddField(
            model_name='materiadaturma',
            name='conteudos',
            field=models.ManyToManyField(to='escola.Conteudo'),
        ),
    ]
