# Generated by Django 2.1.7 on 2019-03-28 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0020_auto_20190328_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkconteudo',
            name='conteudo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='escola.Conteudo'),
            preserve_default=False,
        ),
    ]
