# Generated by Django 2.1.8 on 2019-04-17 19:37

#  Developed by Vinicius José Fritzen
#  Last Modified 17/04/19 16:37.
#  Copyright (c) 2019  Vinicius José Fritzen and Albert Angel Lanzarini

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0023_auto_20190401_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'permissions': (('can_populate_turma', 'Pode popular turmas'), ('can_add_aluno', 'Pode adicionar um aluno a turma.'), ('mudar_horario', 'Pode editar o horario.'), ('can_add_materia', 'Pode adicionar uma materia a turma.'), ('can_add_tarefa', 'Pode adicionar uma tarefa.'))},
        ),
    ]
