# Generated by Django 2.1.8 on 2019-04-28 12:53

#  Developed by Vinicius José Fritzen
#  Last Modified 28/04/19 09:53.
#  Copyright (c) 2019  Vinicius José Fritzen and Albert Angel Lanzarini

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0025_auto_20190425_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='horaFim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='horaInicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='s1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='s2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='s3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='s4',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='s5',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
