# Generated by Django 2.1.8 on 2019-05-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0028_auto_20190519_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provamarcada',
            name='conteudos',
            field=models.ManyToManyField(blank=True, null=True, to='escola.Conteudo'),
        ),
    ]
