# Generated by Django 2.1.8 on 2019-05-25 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0030_auto_20190523_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiadaturma',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='escola.Professor'),
        ),
    ]
