# Generated by Django 2.1.8 on 2019-05-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0031_auto_20190525_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiadaturma',
            name='conteudos',
            field=models.ManyToManyField(blank=True, to='escola.Conteudo'),
        ),
    ]
