# Generated by Django 2.1.8 on 2019-05-26 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0032_auto_20190525_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provaareamarcada',
            name='_prova',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p_area', to='escola.ProvaMarcada'),
        ),
        migrations.AlterField(
            model_name='provamateriamarcada',
            name='_prova',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p_materia', to='escola.ProvaMarcada'),
        ),
    ]
