# Generated by Django 2.1.8 on 2019-05-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0033_auto_20190526_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoturma',
            name='block_prova',
            field=models.BooleanField(default=True),
        ),
    ]
