# Generated by Django 2.2.2 on 2019-06-25 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0034_eventoturma_block_prova'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiadaturma',
            options={'ordering': ['nome', 'area', 'professor'], 'permissions': (('can_edit_materia', 'Pode editar uma materia'), ('can_delete_materia', 'Pode deletar uma materia'))},
        ),
        migrations.AlterField(
            model_name='provaareamarcada',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provas_area', to='escola.AreaConhecimento'),
        ),
        migrations.AlterField(
            model_name='provamateriamarcada',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provas_materia', to='escola.MateriaDaTurma'),
        ),
        migrations.AlterField(
            model_name='turnoaula',
            name='diaDaSemana',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')]),
        ),
    ]
