# Generated by Django 2.2.2 on 2019-07-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0035_auto_20190624_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='deve_enviar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='email_criado',
            field=models.BooleanField(default=False),
        ),
    ]
