# Generated by Django 2.2.2 on 2019-07-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0036_auto_20190705_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receber_email_notificacao',
            field=models.BooleanField(default=True),
        ),
    ]
