# Generated by Django 2.2.2 on 2019-07-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0038_auto_20190707_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificador',
            name='link',
        ),
    ]
