# Generated by Django 2.2.2 on 2019-07-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0039_remove_notificador_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='provamarcada',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
    ]
