# Generated by Django 2.2.2 on 2019-07-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0041_auto_20190708_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
    ]
