# Generated by Django 2.2.2 on 2019-07-09 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escola', '0042_tarefa_notificado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='noti_aviso_geral_professor',
            new_name='noti_aviso_geral_turma',
        ),
        migrations.CreateModel(
            name='AvisoGeral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=170)),
                ('msg', models.TextField()),
                ('destinatarios', models.ManyToManyField(related_name='avisos_recebidos', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avisos_publicados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
