# Generated by Django 2.2.2 on 2019-07-10 11:43

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0043_auto_20190709_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisogeral',
            name='msg',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='descricao',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='linkconteudo',
            name='descricao',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='msg',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefacomentario',
            name='texto',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
