# Generated by Django 2.2.2 on 2019-07-10 12:48

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0044_auto_20190710_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
