# Generated by Django 2.2.2 on 2019-08-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0045_auto_20190710_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['nome'], 'permissions': (('can_add_professor', 'Pode adicionar um novo Professor'), ('can_edit_professor', 'Pode editar um professor'), ('can_delete_professor', 'Pode deletar um professor'))},
        ),
        migrations.AlterField(
            model_name='materiadaturma',
            name='conteudos',
            field=models.ManyToManyField(blank=True, related_name='materias', to='escola.Conteudo'),
        ),
        migrations.AlterField(
            model_name='provamarcada',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prova', to='escola.EventoTurma'),
        ),
        migrations.CreateModel(
            name='EventoEscola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_prova', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.Evento')),
            ],
        ),
    ]
