# Generated by Django 2.0 on 2018-09-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('voting', '0002_auto_20180930_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocao',
            name='porcentagemDaCasa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='mocao',
            name='quorumMinimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
