# Generated by Django 2.0 on 2018-10-01 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('voting', '0003_auto_20180930_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.CasaVotante')),
            ],
        ),
        migrations.CreateModel(
            name='TipoSesao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sessao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='voting.TipoSesao'),
        ),
    ]
