# Generated by Django 2.0 on 2018-10-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('voting', '0004_auto_20181001_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presença',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Cadeira')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Sessao')),
            ],
        ),
    ]
