# Generated by Django 2.0 on 2018-10-01 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('voting', '0005_presença'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Presença',
            new_name='Presenca',
        ),
    ]
