# Generated by Django 2.0 on 2018-10-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('voting', '0006_auto_20181001_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='casa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.CasaVotante'),
        ),
    ]
