# Generated by Django 2.0 on 2018-04-05 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sobrenome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Laitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataDeInicio', models.DateTimeField(null=True, verbose_name='Inicio da Leitura')),
                ('dataDeFim', models.DateTimeField(null=True, verbose_name='Fim da leitura')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13)),
                ('paginas', models.IntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leituras.Autor')),
            ],
        ),
        migrations.AddField(
            model_name='laitura',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leituras.Livro'),
        ),
    ]
