# Generated by Django 2.0 on 2018-04-05 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leituras', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laitura',
            new_name='Leitura',
        ),
    ]
