# Generated by Django 2.0 on 2018-04-08 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leituras', '0003_auto_20180408_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='leituras.Autor')),
            ],
        ),
        migrations.AddField(
            model_name='livro',
            name='nSerie',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leituras.serie'),
        ),
    ]
