# Generated by Django 2.0 on 2018-04-09 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leituras', '0004_auto_20180408_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['sobrenome', 'nome']},
        ),
    ]
