# Generated by Django 2.0 on 2018-09-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leituras', '0006_auto_20180411_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitura',
            name='status',
            field=models.CharField(choices=[('PI', 'Para Iniciar'), ('IN', 'Iniciada'), ('FN', 'Finalizada'), ('AB', 'Abandonada')], default='IN', max_length=2),
        ),
        migrations.AddField(
            model_name='livro',
            name='lido',
            field=models.BooleanField(default=False),
        ),
    ]
