# Generated by Django 2.0 on 2018-09-23 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leituras', '0008_auto_20180921_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editora',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'ordering': ['titulo']},
        ),
        migrations.AlterField(
            model_name='leitura_update',
            name='tipo',
            field=models.CharField(choices=[('IN', 'Iniciada'), ('LD', 'Em leitura'), ('FN', 'Finalizada'), ('AB', 'abadonada')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='livro',
            name='serie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leituras.Serie'),
        ),
    ]
