# Generated by Django 2.1.2 on 2018-10-12 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('leituras', '0013_auto_20181012_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitura',
            name='tipo',
            field=models.CharField(
                choices=[('IN', 'Iniciada'), ('LD', 'Em leitura'), ('FN', 'Finalizada'), ('AB', 'abadonada')],
                default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='livro',
            name='serie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='leituras.Serie'),
        ),
    ]
