# Generated by Django 2.1.2 on 2019-03-04 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leituras', '0017_auto_20190123_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura_update',
            name='tipo',
            field=models.CharField(choices=[('IN', 'Iniciada'), ('LD', 'Em leitura'), ('FN', 'Finalizada'), ('AB', 'Abadonada')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='livro',
            name='serie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leituras.Serie'),
        ),
    ]
