QUOTES = [
    ('Diga-me e eu esquecerei. Ensina-me e eu lembrarei. Envolva-me e eu aprenderei.', 'Benjamin Franklin'),
    ('Desenvolva uma paixão pela aprendizagem. Se você fizer isso, você nunca deixará de crescer.', 'Anthony J. D\'Angelo'),
    ('Pesquisar é criar novo conhecimento.', 'Neil Armstrong'),
    ('O poder é bom e a estupidez é inofensiva, em geral. Mas o poder e a estupidez juntos são um perigo.', 'Patrick Rothfuss'),
    ('[...] as pessoas acreditam em meias verdades e distorções se essas coincidirem com aquilo em que elas querem acreditar, se refletirem os seus medos. ', 'John Flanagan'),
    ('Todo lugar tem suas pequenas superstições, e todo mundo ri do que pensa a gente do outro lado do rio.', 'Patrick Rothfuss'),
    ('Não importa como você leve sua vida, sua inteligência o defenderá melhor do que uma espada. Trate de mantê-la afiada!', 'Patrick Rothfuss'),
    ('É cansativo quando as pessoas se dirigem a nós como se fôssemos crianças, mesmo quando por acaso o somos.', 'Patrick Rothfuss'),
    ('Há três coisas que todo homem sábio deve temer: o mar em uma tempestade, uma noite sem lua, e a ira de um homem gentil.', 'Patrick Rothfuss'),
    ('As corujas são sábias. São cuidadosas e pacientes. A sabedoria impede a audácia – disse. Bebericou de sua caneca, segurando elegantemente a alça entre o polegar e o indicador. – É por isso que as corujas dão maus heróis.', 'Patrick Rothfuss'),
    ('Quer dizer que você saiu em busca de um mito e encontrou um homem.', 'Patrick Rothfuss'),
    ('Tenha pena dele, filhote. Amanhã seguiremos nosso caminho, mas ele terá de suportar sua própria companhia desagradável até o dia em que morrer.', 'Patrick Rothfuss'),
    ('O dia em que nos inquietamos com o futuro é aquele em que deixamos a infância para trás.', 'Patrick Rothfuss'),
    ('Quem consegue encontrar alguém assim, alguém a quem abraçar e com quem fechar os olhos para o mundo, é uma pessoa de sorte. Mesmo que dure apenas um minuto, ou um dia. A imagem deles balançando suavemente ao som da música é como visualizo mentalmente o amor, mesmo decorridos tantos anos.', 'Patrick Rothfuss'),
    ('Por quê? Porque o orgulho é uma coisa estranha, e porque generosidade merece ser retribuída com generosidade. Mas foi sobretudo por me parecer a coisa certa, e essa é uma razão suficiente.', 'Patrick Rothfuss'),
    ('É por isso que as histórias nos atraem. Elas nos dão a clareza e a simplicidade que faltam à vida real.', 'Patrick Rothfuss'),
    ('A música é uma amante orgulhosa e temperamental. Recebendo o tempo e a atenção que merece, ela é sua. Desdenhada, chega o dia em que você chama e ela não responde.', 'Patrick Rothfuss'),
    ('São as perguntas que não sabemos responder que mais nos ensinam. Elas nos ensinam a pensar. Se você dá uma resposta a um homem, tudo o que ele ganha é um fato qualquer. Mas, se você lhe der uma pergunta, ele procurará suas próprias respostas.', 'Patrick Rothfuss'),
    ('Mas não seria terrível? Não seria um horror viver cercada pelo puro e agudo vazio das coisas apenas <em>suficientes</em>?', 'Patrick Rothfuss'),
    ('No final, não nos lembraremos das palavras dos nossos inimigos, mas do silêncio dos nossos amigos.', 'Martin Luther King'),
    ('Aprendi o silêncio com os faladores, a tolerância com os intolerantes, a bondade com os maldosos; e, por estranho que pareça, sou grato a esses professores.', 'Khalil Gibran'),
    ('Se soubéssemos quantas e quantas vezes as nossas palavras são mal interpretadas, haveria muito mais silêncio neste mundo.', 'Oscar Wilde'),
    ('Penso noventa e nove vezes e nada descubro; deixo de pensar, mergulho em profundo silêncio - e eis que a verdade se me revela.', 'Albert Einstein'),
    ('Nós somos mais do que as partes que nos formam.', 'Patrick Rothfuss'),
    ('Os ossos se consolidam. O arrependimento fica com a gente para sempre.', 'Patrick Rothfuss'),
    ('Metade de parecer inteligente tem a ver com ficar de boca fechada nas horas certas.', 'Patrick Rothfuss'),
    # ('', ''),
]
